<Project Sdk="Tizen.NET.Sdk/1.1.7">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>tizen80</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AllowedReferenceRelatedFileExtensions>.doesnotexist</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(FlutterEmbeddingPath)" />
  </ItemGroup>

</Project>
